version: "3.8"
services:
  postgres:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: ppassword
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata