// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: conversations.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const checkConversationParticipants = `-- name: CheckConversationParticipants :many
SELECT conversation_id
from participants p
GROUP BY conversation_id
HAVING array_agg(p.user_id order by p.user_id) =
       array [$1]::uuid[]
`

// эта хня не работает
func (q *Queries) CheckConversationParticipants(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, checkConversationParticipants, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var conversation_id uuid.UUID
		if err := rows.Scan(&conversation_id); err != nil {
			return nil, err
		}
		items = append(items, conversation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (name)
VALUES (null)
returning id, name, private, created_at, deleted_at
`

func (q *Queries) CreateConversation(ctx context.Context) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Private,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, name, private, created_at, deleted_at
from conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Private,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getConversations = `-- name: GetConversations :many
SELECT id, name, private, created_at, deleted_at
FROM conversations
`

func (q *Queries) GetConversations(ctx context.Context) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, getConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Private,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationName = `-- name: SetConversationName :exec
UPDATE conversations
SET name = $2
WHERE id = $1
`

type SetConversationNameParams struct {
	ID   uuid.UUID
	Name *string
}

func (q *Queries) SetConversationName(ctx context.Context, arg SetConversationNameParams) error {
	_, err := q.db.Exec(ctx, setConversationName, arg.ID, arg.Name)
	return err
}
