// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (message, sender_id, conversation_id) VALUES ($1, $2, $3) returning id, message, sender_id, conversation_id, created_at, deleted_at
`

type CreateMessageParams struct {
	Message        string
	SenderID       uuid.UUID
	ConversationID uuid.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Message, arg.SenderID, arg.ConversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.SenderID,
		&i.ConversationID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
