// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        uuid.UUID
	Name      *string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Message struct {
	ID             uuid.UUID
	Message        string
	SenderID       uuid.UUID
	ConversationID uuid.UUID
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Participant struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Login     string
	Password  string
	Salt      []byte
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
