// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: participants.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createParticipant = `-- name: CreateParticipant :exec
INSERT INTO participants (conversation_id, user_id) VALUES ($1, $2)
`

type CreateParticipantParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) error {
	_, err := q.db.Exec(ctx, createParticipant, arg.ConversationID, arg.UserID)
	return err
}
